// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xemlhjvuqxxyswyzyozy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlbWxoanZ1cXh4eXN3eXp5b3p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MjA2MDMsImV4cCI6MjA2NDA5NjYwM30.URA-BboCjVoSjRctpakFJ7CH1A_WwTF_Br7rRKUyKIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);